<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"  name="robot">


    <xacro:include filename="robodog_urdf_parameters.xacro" />
    <xacro:include filename="robodog_inertials.xacro" />
    <xacro:include filename="robodog_p_link.xacro" />
    <xacro:include filename="robodog_r_link.xacro" />
    <xacro:include filename="robodog_s_link.xacro" />
    <xacro:include filename="robodog_base_link.xacro" />
    <xacro:include filename="robodog_left_leg_link.xacro" />
    <xacro:include filename="robodog_right_leg_link.xacro" />
    <xacro:include filename="robodog_lidar.xacro" />
    <xacro:include filename="robodog_gazebo_ros_control_plugins.xacro" />

 
!<!--                       Links                      -->

    <link name="base_inertial">
    <xacro:inertial_box mass="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}" origin="0 0 ${base_height/2}" />
    </link>

    <xacro:base_link name="base_link"/>
    <xacro:left_leg_link name="front_left_leg"/>
    <xacro:left_leg_link name="back_left_leg"/>
    <xacro:right_leg_link name="back_right_leg"/>
    <xacro:right_leg_link name="front_right_leg"/>
    <xacro:lidar_sensor name="front_lidar"  radius="0.05" length="0.02"/>

    
!<!--                           Joints                        -->

 !<!-- WORLD-BASE --> 
    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="base_inertial"/>        
    </joint>

 !<!--BASE-front_left_leg --> 
    <joint name="base_P0_joint" type="fixed">
        <origin xyz="${(base_length/2.0)-(P0_length/2)} ${(base_width/2.0)+(P0_width/2)} ${P0_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_left_leg"/>        
    </joint>

 !<!--BASE-back_left_leg --> 
    <joint name="base_back_left_leg_joint" type="fixed">
        <origin xyz="${-(base_length/2.0)+(P0_length/2)} ${(base_width/2.0)+(P0_width/2)} ${P0_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="back_left_leg"/>        
    </joint>

 !<!--BASE-front_right_leg --> 
    <joint name="base_front_right_leg_joint" type="fixed">
        <origin xyz="${(base_length/2.0)-(P0_length/2)} ${-(base_width/2.0)-(P0_width/2)} ${P0_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="front_right_leg"/>        
    </joint>   

 !<!--BASE-back_right_leg --> 
    <joint name="base_back_right_leg_joint" type="fixed">
        <origin xyz="${-(base_length/2.0)+(P0_length/2)} ${-(base_width/2.0)-(P0_width/2)} ${P0_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="back_right_leg"/>        
    </joint>

 !<!--BASE-front_lidar -->  
    <joint name="front_lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="front_lidar_link"/>
      <origin xyz="${base_length/2} 0 ${base_height}" rpy=" 0 0 0"/>
    </joint>


</robot>